
service: chaining-lambdas-test
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - "*"

functions:
  hello:
    handler: handler.hello
  ciao:
    handler: handler.ciao
    events:
      - sns: ciao-dev
