
service: chaining-lambdas-test
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

functions:
  test:
    handler: handler.test
  test2:
    handler: handler.test2
